/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        industryblack: ["INDUSTRYBLACK", "sans-serif"],
        industryblackitalic: ["INDUSTRYBLACKITALIC", "sans-serif"],
        industrybold: ["INDUSTRYBOLD", "sans-serif"],
        industrybolditalic: ["INDUSTRYBOLDITALIC", "sans-serif"],
        industrybook: ["INDUSTRYBOOK", "sans-serif"],
        industrybookitalic: ["INDUSTRYBOOKITALIC", "sans-serif"],
        industrydemi: ["INDUSTRYDEMI", "sans-serif"],
        industrydemiitalic: ["INDUSTRYDEMIITALIC", "sans-serif"],
        industrylight: ["INDUSTRYLIGHT", "sans-serif"],
        industrylightitalic: ["INDUSTRYLIGHTITALIC", "sans-serif"],
        industrymedium: ["INDUSTRYMEDIUM", "sans-serif"],
        industrymediumitalic: ["INDUSTRYMEDIUMITALIC", "sans-serif"],
        montserratblack: ["MONTSERRATBLACK", "sans-serif"],
        montserratblackitalic: ["MONTSERRATBLACKITALIC", "sans-serif"],
        montserratbold: ["MONTSERRATBOLD", "sans-serif"],
        montserratbolditalic: ["MONTSERRATBOLDITALIC", "sans-serif"],
        montserratextrabold: ["MONTSERRATEXTRABOLD", "sans-serif"],
        montserratextrabolditalic: ["MONTSERRATEXTRABOLDITALIC", "sans-serif"],
        montserratextralight: ["MONTSERRATEXTRALIGHT", "sans-serif"],
        montserratextralightitalic: ["MONTSERRATEXTRALIGHTITALIC", "sans-serif"],
        montserratitalic: ["MONTSERRATITALIC", "sans-serif"],
        montserratlight: ["MONTSERRATLIGHT", "sans-serif"],
        montserratlightitalic: ["MONTSERRATLIGHTITALIC", "sans-serif"],
        montserratmedium: ["MONTSERRATMEDIUM", "sans-serif"],
        montserratmediumitalic: ["MONTSERRATMEDIUMITALIC", "sans-serif"],
        montserratregular: ["MONTSERRATREGULAR", "sans-serif"],
        montserratsemibold: ["MONTSERRATSEMIBOLD", "sans-serif"],
        montserratsemibolditalic: ["MONTSERRATSEMIBOLDITALIC", "sans-serif"],
        montserratthin: ["MONTSERRATTHIN", "sans-serif"],
        montserratthinitalic: ["MONTSERRATTHINITALIC", "sans-serif"],
      },
    },
  },
  plugins: [],
};

